
##################################################
################# Bynary Sensors #################
##################################################

binary_sensor:
  - name: 'Charging Pomodori'
    unique_id: '3398534_is_battery_charging'
    state_topic: 'casaortu/sensors/3398534/is_battery_charging'
    payload_on: 'True'
    payload_off: 'False'
    value_template: '{{value_json.value}}'
    device_class: 'battery_charging'
  - name: 'Charging Peperoni'
    unique_id: '3398804_is_battery_charging'
    state_topic: 'casaortu/sensors/3398804/is_battery_charging'
    payload_on: 'True'
    payload_off: 'False'
    value_template: '{{value_json.value}}'
    device_class: 'battery_charging'
  - name: 'Charging Pothos'
    unique_id: '3398655_is_battery_charging'
    state_topic: 'casaortu/sensors/3398655/is_battery_charging'
    payload_on: 'True'
    payload_off: 'False'
    value_template: '{{value_json.value}}'
    device_class: 'battery_charging'
  - name: 'Charging Ficus'
    unique_id: '3398774_is_battery_charging'
    state_topic: 'casaortu/sensors/3398774/is_battery_charging'
    payload_on: 'True'
    payload_off: 'False'
    value_template: '{{value_json.value}}'
    device_class: 'battery_charging'
  - name: 'Charging Dieffenbachia'
    unique_id: '2548419_is_battery_charging'
    state_topic: 'casaortu/sensors/2548419/is_battery_charging'
    payload_on: 'True'
    payload_off: 'False'
    value_template: '{{value_json.value}}'
    device_class: 'battery_charging'
  - name: 'Charging Patate'
    unique_id: '3399181_is_battery_charging'
    state_topic: 'casaortu/sensors/3399181/is_battery_charging'
    payload_on: 'True'
    payload_off: 'False'
    value_template: '{{value_json.value}}'
    device_class: 'battery_charging'
  - name: 'Charging Rosmarino'
    unique_id: '2548730_is_battery_charging'
    state_topic: 'casaortu/sensors/2548730/is_battery_charging'
    payload_on: 'True'
    payload_off: 'False'
    value_template: '{{value_json.value}}'
    device_class: 'battery_charging'


###########################################
################# Sensors #################
###########################################

sensor:
  - name: 'Temperatura Pomodori'
    unique_id: '3398534_temperature'
    state_topic: 'casaortu/sensors/3398534/temperature'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    value_template: '{{value_json.value}}'
  - name: 'Suolo Pomodori'
    unique_id: '3398534_soil_moisture'
    state_topic: 'casaortu/sensors/3398534/soil_moisture'
    unit_of_measurement: '%'
    device_class: 'moisture'
    value_template: '{{value_json.value}}'
  - name: 'Luminosita Pomodori'
    unique_id: '3398534_luminosity'
    state_topic: 'casaortu/sensors/3398534/luminosity'
    unit_of_measurement: null
    device_class: 'illuminance'
    value_template: '{{value_json.value}}'
  - name: 'Livello Batteria Pomodori'
    unique_id: '3398534_battery_level'
    state_topic: 'casaortu/sensors/3398534/battery_level'
    unit_of_measurement: '%'
    device_class: 'battery'
    value_template: '{{value_json.value}}'
  - name: 'Temperatura Peperoni'
    unique_id: '3398804_temperature'
    state_topic: 'casaortu/sensors/3398804/temperature'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    value_template: '{{value_json.value}}'
  - name: 'Suolo Peperoni'
    unique_id: '3398804_soil_moisture'
    state_topic: 'casaortu/sensors/3398804/soil_moisture'
    unit_of_measurement: '%'
    device_class: 'moisture'
    value_template: '{{value_json.value}}'
  - name: 'Luminosita Peperoni'
    unique_id: '3398804_luminosity'
    state_topic: 'casaortu/sensors/3398804/luminosity'
    unit_of_measurement: null
    device_class: 'illuminance'
    value_template: '{{value_json.value}}'
  - name: 'Livello Batteria Peperoni'
    unique_id: '3398804_battery_level'
    state_topic: 'casaortu/sensors/3398804/battery_level'
    unit_of_measurement: '%'
    device_class: 'battery'
    value_template: '{{value_json.value}}'
  - name: 'Temperatura Pothos'
    unique_id: '3398655_temperature'
    state_topic: 'casaortu/sensors/3398655/temperature'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    value_template: '{{value_json.value}}'
  - name: 'Suolo Pothos'
    unique_id: '3398655_soil_moisture'
    state_topic: 'casaortu/sensors/3398655/soil_moisture'
    unit_of_measurement: '%'
    device_class: 'moisture'
    value_template: '{{value_json.value}}'
  - name: 'Luminosita Pothos'
    unique_id: '3398655_luminosity'
    state_topic: 'casaortu/sensors/3398655/luminosity'
    unit_of_measurement: null
    device_class: 'illuminance'
    value_template: '{{value_json.value}}'
  - name: 'Livello Batteria Pothos'
    unique_id: '3398655_battery_level'
    state_topic: 'casaortu/sensors/3398655/battery_level'
    unit_of_measurement: '%'
    device_class: 'battery'
    value_template: '{{value_json.value}}'
  - name: 'Temperatura Ficus'
    unique_id: '3398774_temperature'
    state_topic: 'casaortu/sensors/3398774/temperature'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    value_template: '{{value_json.value}}'
  - name: 'Suolo Ficus'
    unique_id: '3398774_soil_moisture'
    state_topic: 'casaortu/sensors/3398774/soil_moisture'
    unit_of_measurement: '%'
    device_class: 'moisture'
    value_template: '{{value_json.value}}'
  - name: 'Luminosita Ficus'
    unique_id: '3398774_luminosity'
    state_topic: 'casaortu/sensors/3398774/luminosity'
    unit_of_measurement: null
    device_class: 'illuminance'
    value_template: '{{value_json.value}}'
  - name: 'Livello Batteria Ficus'
    unique_id: '3398774_battery_level'
    state_topic: 'casaortu/sensors/3398774/battery_level'
    unit_of_measurement: '%'
    device_class: 'battery'
    value_template: '{{value_json.value}}'
  - name: 'Temperatura Dieffenbachia'
    unique_id: '2548419_temperature'
    state_topic: 'casaortu/sensors/2548419/temperature'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    value_template: '{{value_json.value}}'
  - name: 'Suolo Dieffenbachia'
    unique_id: '2548419_soil_moisture'
    state_topic: 'casaortu/sensors/2548419/soil_moisture'
    unit_of_measurement: '%'
    device_class: 'moisture'
    value_template: '{{value_json.value}}'
  - name: 'Luminosita Dieffenbachia'
    unique_id: '2548419_luminosity'
    state_topic: 'casaortu/sensors/2548419/luminosity'
    unit_of_measurement: null
    device_class: 'illuminance'
    value_template: '{{value_json.value}}'
  - name: 'Livello Batteria Dieffenbachia'
    unique_id: '2548419_battery_level'
    state_topic: 'casaortu/sensors/2548419/battery_level'
    unit_of_measurement: '%'
    device_class: 'battery'
    value_template: '{{value_json.value}}'


  - name: 'Temperatura Patate'
    unique_id: '3399181_temperature'
    state_topic: 'casaortu/sensors/3399181/temperature'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    value_template: '{{value_json.value}}'
  - name: 'Suolo Patate'
    unique_id: '3399181_soil_moisture'
    state_topic: 'casaortu/sensors/3399181/soil_moisture'
    unit_of_measurement: '%'
    device_class: 'moisture'
    value_template: '{{value_json.value}}'
  - name: 'Luminosita Patate'
    unique_id: '3399181_luminosity'
    state_topic: 'casaortu/sensors/3399181/luminosity'
    unit_of_measurement: null
    device_class: 'illuminance'
    value_template: '{{value_json.value}}'
  - name: 'Livello Batteria Patate'
    unique_id: '3399181_battery_level'
    state_topic: 'casaortu/sensors/3399181/battery_level'
    unit_of_measurement: '%'
    device_class: 'battery'
    value_template: '{{value_json.value}}'

#  - name: 'Temperatura Patate'
#    unique_id: '2549138_temperature'
#    state_topic: 'casaortu/sensors/2549138/temperature'
#    unit_of_measurement: '°C'
#    device_class: 'temperature'
#    value_template: '{{value_json.value}}'
#  - name: 'Suolo Patate'
#    unique_id: '2549138_soil_moisture'
#    state_topic: 'casaortu/sensors/2549138/soil_moisture'
#    unit_of_measurement: '%'
#    device_class: 'moisture'
#    value_template: '{{value_json.value}}'
#  - name: 'Luminosita Patate'
#    unique_id: '2549138_luminosity'
#    state_topic: 'casaortu/sensors/2549138/luminosity'
#    unit_of_measurement: null
#    device_class: 'illuminance'
#    value_template: '{{value_json.value}}'
#  - name: 'Livello Batteria Patate'
#    unique_id: '2549138_battery_level'
#    state_topic: 'casaortu/sensors/2549138/battery_level'
#    unit_of_measurement: '%'
#    device_class: 'battery'
#    value_template: '{{value_json.value}}'

  - name: 'Temperatura Rosmarino'
    unique_id: '2548730_temperature'
    state_topic: 'casaortu/sensors/2548730/temperature'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    value_template: '{{value_json.value}}'
  - name: 'Suolo Rosmarino'
    unique_id: '2548730_soil_moisture'
    state_topic: 'casaortu/sensors/2548730/soil_moisture'
    unit_of_measurement: '%'
    device_class: 'moisture'
    value_template: '{{value_json.value}}'
  - name: 'Luminosita Rosmarino'
    unique_id: '2548730_luminosity'
    state_topic: 'casaortu/sensors/2548730/luminosity'
    unit_of_measurement: null
    device_class: 'illuminance'
    value_template: '{{value_json.value}}'
  - name: 'Livello Batteria Rosmarino'
    unique_id: '2548730_battery_level'
    state_topic: 'casaortu/sensors/2548730/battery_level'
    unit_of_measurement: '%'
    device_class: 'battery'
    value_template: '{{value_json.value}}'


